//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeValue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public long PkRateId { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<decimal> OTBillableRate { get; set; }
        public Nullable<decimal> PremiumBillableRate { get; set; }
        public Nullable<decimal> WageCost { get; set; }
        public Nullable<decimal> Tax1 { get; set; }
        public Nullable<decimal> Tax2 { get; set; }
        public Nullable<decimal> Tax3 { get; set; }
        public Nullable<decimal> Tax4 { get; set; }
        public Nullable<bool> IsDefaultRate { get; set; }
        public Nullable<long> FkFeeTypeId { get; set; }
        public Nullable<long> FkFeeScheduleId { get; set; }
        public Nullable<long> FkGlIncomeAccountId { get; set; }
        public Nullable<long> FkGlExpenseAccountID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> FkCreatedById { get; set; }
        public Nullable<long> FkCompanyId { get; set; }
        public Nullable<long> FkOrganizationId { get; set; }
        public Nullable<long> FkLanguageId { get; set; }
    }
}
