//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeValue.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketMaterialBillLineDetailMap
    {
        public long PkTicketMaterialBillLineDetailMapId { get; set; }
        public Nullable<long> FkBillLineDetailId { get; set; }
        public Nullable<long> FkTicketMaterialId { get; set; }
        public string Item { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> FkCreatedById { get; set; }
        public Nullable<long> FkCompanyId { get; set; }
        public Nullable<long> FkOrganizationId { get; set; }
        public Nullable<long> FkLanguageId { get; set; }
        public Nullable<byte> FkRecordStatusId { get; set; }
    }
}
