//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeValue.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DevTimeValueEntities : DbContext
    {
        public DevTimeValueEntities()
            : base("name=DevTimeValueEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Bill> Bills { get; set; }
        public DbSet<BillLine> BillLines { get; set; }
        public DbSet<BillLineDetail> BillLineDetails { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<ClientAddressMap> ClientAddressMaps { get; set; }
        public DbSet<ClientCommentMap> ClientCommentMaps { get; set; }
        public DbSet<ClientContactMap> ClientContactMaps { get; set; }
        public DbSet<ClientDataMap> ClientDataMaps { get; set; }
        public DbSet<ClientDocumentMap> ClientDocumentMaps { get; set; }
        public DbSet<ClientRateMap> ClientRateMaps { get; set; }
        public DbSet<ClientTeamMap> ClientTeamMaps { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Estimate> Estimates { get; set; }
        public DbSet<EstimateLine> EstimateLines { get; set; }
        public DbSet<EstimateLineDetail> EstimateLineDetails { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<PayrollTimeTracking> PayrollTimeTrackings { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<ProjectAddressMap> ProjectAddressMaps { get; set; }
        public DbSet<ProjectCommentMap> ProjectCommentMaps { get; set; }
        public DbSet<ProjectContactMap> ProjectContactMaps { get; set; }
        public DbSet<ProjectDataMap> ProjectDataMaps { get; set; }
        public DbSet<ProjectDocumentMap> ProjectDocumentMaps { get; set; }
        public DbSet<ProjectRateMap> ProjectRateMaps { get; set; }
        public DbSet<ProjectTeamMap> ProjectTeamMaps { get; set; }
        public DbSet<Rate> Rates { get; set; }
        public DbSet<TicketDisbursmentBillLineDetailMap> TicketDisbursmentBillLineDetailMaps { get; set; }
        public DbSet<TicketDisbursmentEstimateLineDetailMap> TicketDisbursmentEstimateLineDetailMaps { get; set; }
        public DbSet<TicketExpenseBillLineDetailMap> TicketExpenseBillLineDetailMaps { get; set; }
        public DbSet<TicketMaterialEstimateLineDetailMap> TicketMaterialEstimateLineDetailMaps { get; set; }
        public DbSet<TicketServiceBillLineDetailMap> TicketServiceBillLineDetailMaps { get; set; }
        public DbSet<TicketServiceEstimateLineDetailMap> TicketServiceEstimateLineDetailMaps { get; set; }
        public DbSet<TicketTimeEstimateLineDetailMap> TicketTimeEstimateLineDetailMaps { get; set; }
        public DbSet<TicketMaterialBillLineDetailMap> TicketMaterialBillLineDetailMaps { get; set; }
        public DbSet<TicketTimeBillLineDetailMap> TicketTimeBillLineDetailMaps { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Token> Tokens { get; set; }
    }
}
